CREATE TABLE TB_USER(
	USER_NO     NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT USER_NO, USER_ID, USER_PW, USER_NAME,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM TB_USER
ORDER BY USER_NO ;

SELECT USER_NO, USER_ID, USER_PW, USER_NAME,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM TB_USER
WHERE USER_NAME LIKE '%' || ? || '%'
ORDER BY USER_NO;


SELECT * FROM TB_USER;

UPDATE TB_USER 
SET USER_NAME= '김아무무'
WHERE USER_ID = 'user03'     
AND USER_PW = 'pass03';   
    
-- 1번 예시
INSERT INTO TB_USER VALUES(
SEQ_USER_NO.NEXTVAL,'user04', 'pass04','유저4', DEFAULT);
)

SELECT COUNT(*)
FROM TB_USER
WHERE USER_ID = 'user01';


--김영희 회원과 같은 지역에 사는 회원들의 지역명, 아이디, 이름, 등급명을 이름 오름차순으로 조회


 -- 노옹철과 같은 지역에 사는 사원의 지역명, 사번, 이름 직급명을 이름 오름차순

SELECT * FROM EMPLOYEE;

SELECT DEPT_TITLE 지역명, EMPLOYEE.EMP_NO  아이디, EMP_NAME 이름, 
JOB_NAME 등급명
FROM EMPLOYEE MAIN
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE JOB_CODE = (
             SELECT JOB_CODE
             FROM EMPLOYEE SUB
             WHERE EMP_NAME = '노옹철')
ORDER BY EMP_NAME DESC;​


COMMIT;














